# Generated by Django 5.1.4 on 2025-01-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_application_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school_name',
            new_name='name',
        ),
    ]
